In [35]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np

In [36]:
def log_loss(y_true, y_predicted):
    epsilon=1e-15
    y_=[max(i,epsilon) for i in y_predicted]
    y_=[min(i,1-epsilon) for i in y_]
    y_= np.array(y_)
    return -np.mean(y_true*np.log(y_) +(1-y_true)* np.log(1-y_))

In [37]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

log_loss(y_true,y_predicted)

17.2696280766844

In [38]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [105]:
# From scratch

class myNN:
    
    def __init__(self):
        self.w1=1
        self.w2=1
        self.bias=0
    
    def gradient_descent(self,age,affordability,y_true,epochs,loss_thresold):
        rate=0.05
        n=len(age)
        
        for i in range(epochs):
            weighted_sum=self.w1*age+self.w2*affordability+self.bias
            y_=sigmoid_numpy(weighted_sum)
            loss=log_loss(y_true,y_)
            wd1=np.dot(np.transpose(age),(y_-y_true))
            wd2=np.dot(np.transpose(affordability),(y_-y_true))
            db=np.mean(y_-y_true)
            
            self.w1=self.w1-rate*wd1
            self.w2=self.w2-rate*wd2
            self.bias=self.bias-rate*db
            
            if i%50==0:
                print(f'Epoch:{i}, w1:{self.w1}, w2:{self.w2}, bias:{self.bias},loss:{loss}')
            if loss<=loss_thresold:
                print(f'Epoch:{i}, w1:{self.w1}, w2:{self.w2}, bias:{self.bias},loss:{loss}')
                break
        
            
    
    def predict(self,X_test):
        weighted_sum= self.w1* X_test['Age']+self.w2*X_test['Daily Time Spent on Site']+self.bias
        return sigmoid_numpy(weighted_sum)
    
    def fit(self,X,y,epochs,loss_thresold):
        #call gradient descent here...
        self.gradient_descent(X['Age'],X['Daily Time Spent on Site'],y,epochs,loss_thresold)
        

In [41]:
from sklearn.model_selection import train_test_split
datapath="D:/Machine Learning Datasets/ad_click.csv"
data=pd.read_csv(datapath)
data.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

In [61]:

X = data.drop(['Timestamp', 'Clicked on Ad', 'Ad Topic Line', 'Country', 'City','Area Income','Daily Internet Usage','Male'], axis=1)
y = data['Clicked on Ad']
X['Age']=X['Age']/100
X['Daily Time Spent on Site']=X['Daily Time Spent on Site']/100
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)



In [62]:
X

Daily Time Spent on Site   Age
0                      0.6895  0.35
1                      0.8023  0.31
2                      0.6947  0.26
3                      0.7415  0.29
4                      0.6837  0.35
..                        ...   ...
995                    0.7297  0.30
996                    0.5130  0.45
997                    0.5163  0.51
998                    0.5555  0.19
999                    0.4501  0.26

[1000 rows x 2 columns]

In [63]:
y

0      0
1      0
2      0
3      0
4      0
      ..
995    1
996    1
997    1
998    0
999    1
Name: Clicked on Ad, Length: 1000, dtype: int64

In [64]:
max(X['Daily Time Spent on Site'])
np.mean(X['Daily Time Spent on Site'])

0.6500020000000004

In [65]:
np.mean(X['Age'])


0.36008999999999974

In [66]:
# building model using keras.
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',
                      kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.fit(X_train,y_train,epochs=1000)

Epoch 1/1000
22/22 [==============================] - 1s 3ms/step - loss: 0.8563 - accuracy: 0.4943
Epoch 2/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.8458 - accuracy: 0.4943
Epoch 3/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.8358 - accuracy: 0.4943
Epoch 4/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.8266 - accuracy: 0.4943
Epoch 5/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.8176 - accuracy: 0.4943
Epoch 6/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.8090 - accuracy: 0.4943
Epoch 7/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.8013 - accuracy: 0.4943
Epoch 8/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.7936 - accuracy: 0.4943
Epoch 9/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.7866 - accuracy: 0.4943
Epoch 10/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.7801 - accuracy: 0.4943

22/22 [==============================] - 0s 3ms/step - loss: 0.6648 - accuracy: 0.7143
Epoch 83/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.6639 - accuracy: 0.7157
Epoch 84/1000
22/22 [==============================] - 0s 4ms/step - loss: 0.6631 - accuracy: 0.7200
Epoch 85/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.6622 - accuracy: 0.7229
Epoch 86/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.6613 - accuracy: 0.7214
Epoch 87/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.6605 - accuracy: 0.7257
Epoch 88/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.6597 - accuracy: 0.7271
Epoch 89/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.6588 - accuracy: 0.7286
Epoch 90/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.6580 - accuracy: 0.7386
Epoch 91/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.6571 - accuracy: 0.7400
Epoc

22/22 [==============================] - 0s 2ms/step - loss: 0.5973 - accuracy: 0.8429
Epoch 163/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5965 - accuracy: 0.8443
Epoch 164/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5957 - accuracy: 0.8443
Epoch 165/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5949 - accuracy: 0.8429
Epoch 166/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5942 - accuracy: 0.8429
Epoch 167/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5934 - accuracy: 0.8457
Epoch 168/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5926 - accuracy: 0.8457
Epoch 169/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5918 - accuracy: 0.8457
Epoch 170/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5910 - accuracy: 0.8471
Epoch 171/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5902 - accuracy: 0.

22/22 [==============================] - 0s 3ms/step - loss: 0.5387 - accuracy: 0.8700
Epoch 243/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5380 - accuracy: 0.8714
Epoch 244/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5373 - accuracy: 0.8700
Epoch 245/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5367 - accuracy: 0.8700
Epoch 246/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5360 - accuracy: 0.8700
Epoch 247/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5354 - accuracy: 0.8714
Epoch 248/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5348 - accuracy: 0.8729
Epoch 249/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5341 - accuracy: 0.8729
Epoch 250/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5334 - accuracy: 0.8729
Epoch 251/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.5327 - accuracy: 0.

22/22 [==============================] - 0s 2ms/step - loss: 0.4901 - accuracy: 0.8800
Epoch 323/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4896 - accuracy: 0.8800
Epoch 324/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4890 - accuracy: 0.8800
Epoch 325/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4885 - accuracy: 0.8800
Epoch 326/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4879 - accuracy: 0.8786
Epoch 327/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4874 - accuracy: 0.8800
Epoch 328/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4868 - accuracy: 0.8786
Epoch 329/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4863 - accuracy: 0.8786
Epoch 330/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4857 - accuracy: 0.8786
Epoch 331/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4852 - accuracy: 0.

22/22 [==============================] - 0s 3ms/step - loss: 0.4502 - accuracy: 0.8843
Epoch 403/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4498 - accuracy: 0.8843
Epoch 404/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4493 - accuracy: 0.8843
Epoch 405/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4489 - accuracy: 0.8843
Epoch 406/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4485 - accuracy: 0.8843
Epoch 407/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4481 - accuracy: 0.8829
Epoch 408/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4476 - accuracy: 0.8843
Epoch 409/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4472 - accuracy: 0.8843
Epoch 410/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4467 - accuracy: 0.8843
Epoch 411/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4463 - accuracy: 0.

22/22 [==============================] - 0s 2ms/step - loss: 0.4181 - accuracy: 0.8871
Epoch 483/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4177 - accuracy: 0.8871
Epoch 484/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4173 - accuracy: 0.8871
Epoch 485/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4170 - accuracy: 0.8871
Epoch 486/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4166 - accuracy: 0.8871
Epoch 487/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4163 - accuracy: 0.8871
Epoch 488/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4159 - accuracy: 0.8871
Epoch 489/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4156 - accuracy: 0.8871
Epoch 490/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4152 - accuracy: 0.8871
Epoch 491/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4149 - accuracy: 0.

22/22 [==============================] - 0s 2ms/step - loss: 0.3927 - accuracy: 0.8900
Epoch 563/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3924 - accuracy: 0.8900
Epoch 564/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3922 - accuracy: 0.8900
Epoch 565/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3919 - accuracy: 0.8900
Epoch 566/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3916 - accuracy: 0.8886
Epoch 567/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3913 - accuracy: 0.8900
Epoch 568/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3910 - accuracy: 0.8914
Epoch 569/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3908 - accuracy: 0.8900
Epoch 570/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3905 - accuracy: 0.8929
Epoch 571/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3902 - accuracy: 0.

22/22 [==============================] - 0s 3ms/step - loss: 0.3722 - accuracy: 0.8971
Epoch 643/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3719 - accuracy: 0.8971
Epoch 644/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3717 - accuracy: 0.8971
Epoch 645/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3715 - accuracy: 0.8971
Epoch 646/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3713 - accuracy: 0.8971
Epoch 647/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3710 - accuracy: 0.8971
Epoch 648/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3708 - accuracy: 0.8971
Epoch 649/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3706 - accuracy: 0.8971
Epoch 650/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3703 - accuracy: 0.8971
Epoch 651/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3701 - accuracy: 0.

22/22 [==============================] - 0s 2ms/step - loss: 0.3556 - accuracy: 0.8971
Epoch 723/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3554 - accuracy: 0.8971
Epoch 724/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3553 - accuracy: 0.8986
Epoch 725/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3551 - accuracy: 0.8971
Epoch 726/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3549 - accuracy: 0.8971
Epoch 727/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3547 - accuracy: 0.8971
Epoch 728/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3545 - accuracy: 0.8971
Epoch 729/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3543 - accuracy: 0.8986
Epoch 730/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3542 - accuracy: 0.8986
Epoch 731/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3540 - accuracy: 0.

22/22 [==============================] - 0s 2ms/step - loss: 0.3422 - accuracy: 0.9014
Epoch 803/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3421 - accuracy: 0.9014
Epoch 804/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3419 - accuracy: 0.9014
Epoch 805/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3417 - accuracy: 0.9014
Epoch 806/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3416 - accuracy: 0.9014
Epoch 807/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3415 - accuracy: 0.9014
Epoch 808/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3413 - accuracy: 0.9014
Epoch 809/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3411 - accuracy: 0.9014
Epoch 810/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3410 - accuracy: 0.9014
Epoch 811/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3409 - accuracy: 0.

22/22 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.9000
Epoch 883/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3310 - accuracy: 0.9000
Epoch 884/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3308 - accuracy: 0.9000
Epoch 885/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3307 - accuracy: 0.9000
Epoch 886/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3306 - accuracy: 0.9000
Epoch 887/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3305 - accuracy: 0.9000
Epoch 888/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3303 - accuracy: 0.9000
Epoch 889/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3302 - accuracy: 0.9000
Epoch 890/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3301 - accuracy: 0.9000
Epoch 891/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.3300 - accuracy: 0.

22/22 [==============================] - 0s 2ms/step - loss: 0.3219 - accuracy: 0.9000
Epoch 963/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3217 - accuracy: 0.9000
Epoch 964/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3216 - accuracy: 0.9000
Epoch 965/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3216 - accuracy: 0.9000
Epoch 966/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3214 - accuracy: 0.9000
Epoch 967/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3213 - accuracy: 0.9000
Epoch 968/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3213 - accuracy: 0.9000
Epoch 969/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3211 - accuracy: 0.9000
Epoch 970/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3210 - accuracy: 0.9000
Epoch 971/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.3209 - accuracy: 0.

In [69]:
model.evaluate(X_test,y_test)

10/10 [==============================] - 0s 2ms/step - loss: 0.3152 - accuracy: 0.8867


[0.3152468502521515, 0.8866666555404663]

In [87]:
X_test

Daily Time Spent on Site   Age
688                    0.7458  0.36
49                     0.4801  0.46
288                    0.4505  0.42
698                    0.8676  0.28
775                    0.4388  0.54
..                        ...   ...
635                    0.3576  0.51
209                    0.4015  0.38
296                    0.7395  0.35
609                    0.8429  0.30
63                     0.8606  0.32

[300 rows x 2 columns]

In [86]:
model.predict(X_test)

10/10 [==============================] - 0s 2ms/step


array([[0.3256777 ],
       [0.92555314],
       [0.9169662 ],
       [0.07326359],
       [0.97418356],
       [0.09035004],
       [0.10955467],
       [0.97134215],
       [0.28588387],
       [0.96762085],
       [0.2007085 ],
       [0.19304489],
       [0.16949955],
       [0.8042816 ],
       [0.39738616],
       [0.3615887 ],
       [0.8710472 ],
       [0.9233981 ],
       [0.15560475],
       [0.2582831 ],
       [0.16244006],
       [0.10507439],
       [0.13860357],
       [0.14412434],
       [0.7317008 ],
       [0.37393895],
       [0.12308688],
       [0.8767748 ],
       [0.96356076],
       [0.9696184 ],
       [0.30342966],
       [0.12291574],
       [0.18582293],
       [0.09980222],
       [0.22695105],
       [0.36841878],
       [0.15556997],
       [0.21897253],
       [0.83113307],
       [0.9214243 ],
       [0.21745142],
       [0.12523158],
       [0.0947406 ],
       [0.0915244 ],
       [0.15598737],
       [0.09977507],
       [0.22528502],
       [0.243

In [70]:
coef, intercept=model.get_weights()
coef, intercept

(array([[-8.689725],
        [ 9.392462]], dtype=float32),
 array([2.3717105], dtype=float32))

In [106]:
myModel=myNN()
myModel.fit(X_train,y_train,epochs=10000,loss_thresold=0.2905)


Epoch:0, w1:-1.2817293818661963, w2:-6.628779034379488, bias:-0.011923370157777372,loss:0.8613265476950211
Epoch:50, w1:22.422769114207057, w2:-12.507851943936815, bias:0.06609775907521857,loss:0.3092098257610647
Epoch:100, w1:22.460647449010366, w2:-12.20545265254952, bias:0.10222168907506127,loss:0.305272650290943
Epoch:150, w1:22.36961364403727, w2:-12.191704608428495, bias:0.13761029136533853,loss:0.30475748455546214
Epoch:200, w1:22.295707913770524, w2:-12.203413687341616, bias:0.17282848071440168,loss:0.30425801178847683
Epoch:250, w1:22.233320078796805, w2:-12.221869177684788, bias:0.207883403367698,loss:0.3037639708211571
Epoch:300, w1:22.17695536917878, w2:-12.243225046676827, bias:0.24276813005049364,loss:0.3032750394460703
Epoch:350, w1:22.123765281236594, w2:-12.265949822731628, bias:0.27747910798965464,loss:0.3027911110613294
Epoch:400, w1:22.072351669349445, w2:-12.289325407507235, bias:0.31201505834595666,loss:0.30231212081975817
Epoch:450, w1:22.022033267714566, w2:-12.

In [91]:
coef, intercept=model.get_weights()
coef, intercept

(array([[-8.689725],
        [ 9.392462]], dtype=float32),
 array([2.3717105], dtype=float32))

In [107]:
myModel.w1

20.81466987351796

In [102]:
myModel.w2

-73.60054645457535

In [103]:
myModel.bias

25.77957702032301

In [108]:
myModel.predict(X_test)

688    0.279609
49     0.989843
288    0.984179
698    0.014913
775    0.998865
         ...   
635    0.999260
209    0.980793
296    0.254855
609    0.030650
63     0.036715
Length: 300, dtype: float64